import Head from 'next/head'
import Link from "next/link";
import Achievements from '../components/Achievements'
import Hero from '../components/Hero'
import "slick-carousel/slick/slick.css"; 
import "slick-carousel/slick/slick-theme.css";
import Welcome from '../components/Welcome';

export default function Home() {
  return (
    <div>
      <Head>
        <title>7Sins eSports</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-gray-900 pb-5'>
        <Welcome />
        <Achievements />
        {/* === lineup === */}
        <div>
          <Hero />
          <Link href='/lineup'>
            <button className="block m-auto bg-gray-800 py-2 px-3 text-white rounded text-xs my-3">More Details</button>
          </Link>
        </div>
      
      </main>
    </div>
  )
}
