import Head from 'next/head'
import Achievements from '../components/Achievements'
import Hero from '../components/Hero'
import "slick-carousel/slick/slick.css"; 
import "slick-carousel/slick/slick-theme.css";
import Welcome from '../components/Welcome';

export default function Home() {
  return (
    <div>
      <Head>
        <title>7Sins eSports</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-gray-900'>
        <Welcome />
        <Achievements />
        <Hero />
      </main>
    </div>
  )
}
